### PR TITLE
Test all examples with travis

### LINKED ISSUE #58: Test examples with travis
We should build all the examples with travis as well. As inspiration for a `.travis.yml` that works for several cabal packages in the same repository, have a look [here](https://github.com/turion/rhine/blob/dev_rhine_gloss/.travis.yml).

### PR DESCRIPTION
**Pull request by turion**
* [x] Tested all examples
* [x] Updated to be compatible with the newest version of `base`
* [x] Added all examples to `.travis.yml`
* [ ] Modified deploy condition to only upload dunai and bearriver

_Warning:_ Before merging this, someone needs to review and/or test whether the deploy condition in `.travis.yml` works correctly. I don't know how to test this without actually triggering a release.

### CODE REVIEW

**Comment by turion** [comment]
Currently, the 7.6.3 cases fail because the version of bearriver on hackage requires `base>=4.7`. This is already fixed in `develop`, but not released yet.

**Comment by turion** [comment]
* Some examples (`bouncingball`, `haskanoid`, ...) require external libraries. Those add 
* There seems to be a [bug](https://sourceforge.net/p/wxhaskell/bugs/116/) in `wxcore` which prevents [some GHC 8.2.1 jobs](https://travis-ci.org/ivanperez-keera/dunai/jobs/326844410) from completing.
* There is a strange error `configure: error: C compiler cannot create executables` (travis bug?) which prevents [haskanoid](https://travis-ci.org/ivanperez-keera/dunai/jobs/326821294) from completing.

**Comment by ivanperez-keera** [comment]
>    Some examples (bouncingball, haskanoid, ...) require external libraries. Those add about 10 seconds to each job.

Does this change anything, regarding any decisions to be made wrt to accepting or rejecting the PR?

>    There seems to be a bug in wxcore which prevents discrete and keerahails on GHC 8.2.1 from completing.

Has this bug been reported to wxcore? Can this case be disabled so that it does not cause the travis job to fail.

>    There is a strange error configure: error: C compiler cannot create executables (travis bug?) which prevents haskanoid from completing.

Unless haskanoid is not compiled with the rest of the examples, this breaks the travis job. It either needs to be fixed (here or in the haskanoid project), or disabled (if it currently is already disabled, which I guess is the case).

**Comment by turion** [comment]
>>    Some examples (bouncingball, haskanoid, ...) require external libraries. Those add about 10 seconds to each job.

> Does this change anything, regarding any decisions to be made wrt to accepting or rejecting the PR?

No, unless you want to optimise the duration of a travis run.

>>    There seems to be a bug in wxcore which prevents discrete and keerahails on GHC 8.2.1 from completing.

> Has this bug been reported to wxcore? Can this case be disabled so that it does not cause the travis job to fail.

Yes, I reported it: https://sourceforge.net/p/wxhaskell/bugs/116/
I believe this case could be disabled with a travis build matrix condition, but I'm not entirely sure how.

>>    There is a strange error configure: error: C compiler cannot create executables (travis bug?) which prevents haskanoid from completing.

> Unless haskanoid is not compiled with the rest of the examples, this breaks the travis job. It either needs to be fixed (here or in the haskanoid project), or disabled (if it currently is already disabled, which I guess is the case).

I don't understand. (How) Does haskanoid depend on other examples?

**Comment by ivanperez-keera** [comment]
Currently, several examples are broken. See: https://travis-ci.org/ivanperez-keera/dunai/builds/326844429

**Comment by ivanperez-keera** [comment]
>     Unless haskanoid is not compiled with the rest of the examples, this breaks the travis job.
> 
> I don't understand. (How) Does haskanoid depend on other examples?
> 

It doesn't, but it is included in the tests. It needs to be fixed or that test disabled.

**Comment by turion** [comment]
I don't know how to fix any of the remaining problems. Of course, we can always take them out of the build matrix, but is that acceptable?

**Comment by ivanperez-keera** [comment]
Some packages are not compiling due to their version boundaries in their respective cabal files. I'm not sure those are there because they need to, or because they were the default upon `cabal init`.

Those issues can be fixed. For everything else, I'm happy disabling some tests for now and revisiting this in the future.

This is already an improvement over what we had.

**Comment by turion** [comment]
The version boundary issue is already fixed in `develop`. The reason it's not fixed on travis is because travis downloads dependencies from hackage, not from the repo. We could change this with adding sandboxes and add-source dependencies to the build process.

**Comment by ivanperez-keera** [comment]
> The version boundary issue is already fixed in develop. 

Maybe for `bearriver`, but not for all the examples. Look:

```
$ grep -nHre '\<base\>'  --include='*.cabal' | column -t | grep -oe '^[^,]*' | sort -g
basic-examples/basic-examples.cabal:22:                   build-depends:  base  >=4.8  &&   <4.9
bearriver/bearriver.cabal:26:                             build-depends:  base  >=4.6  &&   <5
bouncingball/bearriver-examples-bouncingball.cabal:20:    build-depends:  base  >=4.6  &&   <      5
bouncingball/bearriver-examples-bouncingball.cabal:31:    build-depends:  base  >=4.6  &&   <      5
classicfrp/classicfrp.cabal:22:                           build-depends:  base  >=4.8  &&   <4.9
classicfrp/classicfrp.cabal:31:                           build-depends:  base  >=4.8  &&   <4.9
discrete/dunai-examples-discreterp-wxhaskell.cabal:14:    build-depends:  base  >=4.7  &&   <4.9
discrete/dunai-examples-discreterp-wxhaskell.cabal:19:    build-depends:  base  >=4.7  &&   <4.9
haskanoid/haskanoid.cabal:102:                            build-depends:  base  >=     4.6  &&     <             5
keerahails/dunai-examples-keerahails-wxhaskell.cabal:14:  build-depends:  base  >=4.7  &&   <4.9
list/bearriver-examples-bouncingball-list.cabal:19:       build-depends:  base  >=4.6  &&   <      5
paper/dunai-examples-paper.cabal:16:                      build-depends:  base  >=4.6  &&   <5
reversefrpzoo/wormholes/dunai-frp-wormholes.cabal:16:     build-depends:  base  >=4.6  &&   <      5
taggingmonad/taggingmonad.cabal:23:                       build-depends:  base  >=4.8  &&   <4.9

```

**Comment by turion** [comment]
Oh, my bad, sorry. What we want, according to [this table](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory), is `base >= 4.6` as long as we're sticking to GHC 7.6.3.

**Pull request merged**
