### PR TITLE
Adds unfoldM (unfolding with Kleisli arrows)

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
Hi. Just to let you know, I won't be merging new features until the renaming is complete. I want to plan versions well and finish new versions one by one.

**Comment by ivanperez-keera** [comment]
Please, keep this in your projects until further notice.

This is yet another case in which everybody has been told this would be frozen until other tasks were done. A lot of good work has been done in dunai (with papers, a presentation at ICFP, draft implementation with indexed monads, and new projects being open) and rhine (with a paper and a presentation at Haskell symposium 10 days ago).

It's ok not to suddenly try to elevate the priority of these tasks by saying "now that you are back if you don't move quickly I'll fork". It's really selfish.

Please, consider that other people have lives to, things to attend to, they are working day and night to make things happen, you are also benefiting from those efforts, and you have no right to exercise additional pressure.

**Comment by turion** [comment]
> It's ok not to suddenly try to elevate the priority of these tasks by saying "now that you are back if you don't move quickly I'll fork". It's really selfish.
> Please, consider that other people have lives to, things to attend to, they are working day and night to make things happen, you are also benefiting from those efforts, and you have no right to exercise additional pressure.

I'm surprised by your emotional reaction and won't discuss this in public. I will contact you in private.

**Comment by ivanperez-keera** [comment]
> I'm surprised by your emotional reaction and won't discuss this in public. I will contact you in private.

Please don't. We've been over this many times. I'm not going to engage in any kind of discussion about this anymore.

**Pull request closed without merging**
