### PR TITLE
Issue12

### LINKED ISSUE #12: Rewrite all accumulation functions
They're all special cases of `accumulateWith`

### PR DESCRIPTION
**Pull request by turion**
Fixes #12. Compiles. If you're unhappy to see the variant with `feedback` go, then comment and I'll rewrite `accumulateWith` in terms of `feedback`.

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
I'd say `feedback` seems more fundamental than `accumulateWith`. If so, then it would be best to implement `accumulateWith` with `feedback`, which seems trivially possible.

**Comment by ivanperez-keera** [comment]
Would you mind renaming this branch as develop_issue12, and possibly develop_some_significant_name, so that it's clear by the name what the branch is about, and how it is related to other branches?

**Comment by turion** [comment]
Ok, I'll rewrite `accumulateWith` with feedback, it makes sense. Can we expect performance problems from this, or should I inline it?

I'll happily rename the branch to develop_issue12_rewrite_accumulation_functions, but the only way I know is by creating a new branch and deleting the old one including the pull request... not sure how to do this cleverly.

**Comment by ivanperez-keera** [comment]
There will be a small (linear) overhead from using `arr`. I would not inline anything for now. I'd avoid optimisations for now.

Renaming git branch: Rename locally, remove remotely, push new (old branch) remotely. Yes, pull request could be lost.

**Pull request closed without merging**
