### PR TITLE
Added notice to readme about the bearriver arcade

### PR DESCRIPTION
**Pull request by walseb**
#223

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
Thanks!

To keep things documented, could I ask you that you please refer, in the commit message, to the issue that you opened, with the text `Refs #223` ?

Also, I'm not sure what more can be said that could be meaningful, but if you can think of something else, you can add it to the same message. Just imagine the github repo was lost and someone that's never seen dunai had to go through the commit messages to understand what happened. What would you tell them that could be helpful beyond the top line? If anything, then please write that too :)

**Comment by walseb** [comment]
Sure! I will fix it tomorrow

**Comment by walseb** [comment]
I have changed the commit messages in this repo and yampa now

**Comment by ivanperez-keera** [comment]
Hi! Thanks!

I have modified it a bit (both the message and the entry), but your authorship is respected :) It's merged but github won't detect it because I amended the commit message.

**Pull request closed without merging**
