### PR TITLE
Add haskanoid entry to Games section. Refs #227

### PR DESCRIPTION
**Pull request by mezzomondo**
Commit ivanperez-keera/haskanoid@cb50205bd8e1ec92eae3b689c1e4f3f2c260367d
added bearriver support to the official haskanoid distribution, making it
a candidate to be listed as a dunai/bearriver game.

Consequently, this commit modifies the README to list haskanoid in the Games section.

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
@mezzomondo  Thanks! This is nearly perfect, but there is a typo!!!

You added it to the readme as `Harkanoids`, not `Haskanoid`.

Please, just edit the commit and force push the change (it makes little sense to have 2 commits for such a small change).

I'll keep an eye out and merge it when it's pushed. Thanks!

**Comment by mezzomondo** [comment]
Lol sorry, one sec...

**Comment by ivanperez-keera** [comment]
Thanks! :smile:  If you know how it, it would be easier to just squash the two commits into one keeping only the original commit message. If not, I can do it.

**Comment by mezzomondo** [comment]
Can you do just a "squash and merge"? I'm pretty sure that if I start rebasing I'll make more mess :)

**Comment by ivanperez-keera** [comment]
Merged and closed.

**Pull request closed without merging**
