### PR TITLE
Added Related Projects Section

### PR DESCRIPTION
**Pull request by dynomite567**
Solves issues #133 and #134 by adding a Related projects section in the README.md file

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
Thanks, @dynomite567 . There's also a "Rhine: FRP with type-level clocks" paper that could be included. Can you add a commit with that as well as part of #133 ?

**Comment by dynomite567** [comment]
Just want to make sure before I add it, this is it right?
https://dl.acm.org/citation.cfm?id=3242757

**Comment by dynomite567** [comment]
Done. Also rebased with latest commits to avoid conflicts.

**Comment by ivanperez-keera** [comment]
Thanks!

**Pull request merged**
