### PR TITLE
Fix & CI classicfrp example

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
@turion I think this may work now that #208 is fixed.

Could you please rebase it on top of the new develop and document your change both with an issue that clearly explains the comment and in the commit message?

(Reasoning: Trying to keep everything well documented :) )

**Comment by turion** [comment]
Closes #214.

**Comment by ivanperez-keera** [comment]
The latest change adds dunai-test, but it breaks the CI. It appears to be a missing `Functor` constraint. Can you please check and get the CI to build correctly before I evaluate the PR for merging?

**Comment by ivanperez-keera** [comment]
Rebased and merged into develop.

**Pull request closed without merging**
