### PR TITLE
Dev concat s

### PR DESCRIPTION
**Pull request by turion**
Added utility to concatenate an MStream of lists

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
Also, why not make it polymorphic in the input?

 
```
-- | Concatenates a monadic stream of lists to a monadic stream.
concatS :: Monad m => MSF m a [b] -> MSF m a b
concatS msf = MSF $ tick msf []
  where
    tick msf (b:bs) a = return (b, MSF $ tick msf bs)
    tick msf []     a = do
      (bs, msf') <- unMSF msf a
      tick msf' bs a
```

**Comment by turion** [comment]
> Just in case: have you thought about the alternative implementation in which the internal `MSF` steps at every sample, regardless of whether the accumulator is empty or not?

I think that doesn't work. Imagine an `MSF` that outputs a list of length 2 at every step. The accumulator would grow indefinitely.

**Comment by ivanperez-keera** [comment]
Yes. Well, it works differently :) Your way, it introduces asynchronicity.

Would it be safe to say that, up until now, everything else is synchronous?

So far, don't all MSFs tick exactly once per sampling time, unless you access the constructor for MSFs.

**Comment by turion** [comment]
> Also, why not make it polymorphic in the input?

That would be nice, but it looses data every time a nonempty list is produced.

If I had incoming data for every element of the list, I'd first apply mapMSF:
```
produceLists :: MSF m () [a]
processStuff :: MSF m a b
produceBs :: MSF m () b
produceBs = concatS $ produceLists >>> mapMSF processStuff
```

**Comment by turion** [comment]
> Yes. Well, it works differently :) Your way, it introduces asynchronicity.
Would it be safe to say that, up until now, everything else is synchronous?
So far, don't all `MSF`s tick exactly once per sampling time, unless you access the constructor for `MSF`s.

Very good point. Yes, actually that's exactly the reason I implemented it. Using `concatS`, one can do more general things like asynchronously merging/zipping to `MSF`s etc.
Are you saying we should somehow document this difference?

**Comment by ivanperez-keera** [comment]
>     Also, why not make it polymorphic in the input?
> 
> That would be nice, but it looses data every time a nonempty list is produced.

I don't get it. It's just a generalisation of your implementation, isn't it? You are just assuming that the input is of type `()`:

`yourConcatS = arr (const ()) >>> myConcatS `

**Comment by turion** [comment]
> Also, both implementations have the precondition that the MSF must produce a non-empty list at every point

I don't think so. The only precondition is that the MSF must _eventually_ produce a non-empty list. If it starts producing empty lists _forever_, then yes, it hangs up.

**Comment by ivanperez-keera** [comment]
> > Also, both implementations have the precondition that the MSF must produce a non-empty list at every point
> 
> I don't think so. The only precondition is that the MSF must eventually produce a non-empty list. If it starts producing empty lists forever, then yes, it hangs up.

There's a difference between forever/eventually at this conceptual sampling time, and forever/eventually at some future sampling time.

By _at every point_ I mean that it needs to produce some output without the monadic context changing due to other MSFs in the network.

**Comment by turion** [comment]
> But this pull request includes the changes in #30 .

Oops, my bad. I'll have to pay more attention. Anyways, that's merged now.

**Comment by turion** [comment]
> By _at every point_ I mean that it needs to produce some output without the monadic context changing due to other MSFs in the network.

I'm not sure I'm following entirely. Consider the following examples:
```
everyOtherEmpty = proc _ -> do
  n <- count -< ()
  returnA -< if even n
    then [ "Hello" ]
    else []

after3Empty = proc _ -> do
  n <- count -< ()
  returnA -< if n > 3
    then []
    else [ "Hello" ]
```
Do we agree that `concatS everyOtherEmpty` is ok and will be productive, while `concatS after3Empty` will hang up?

**Comment by ivanperez-keera** [comment]
> Do we agree that `concatS everyOtherEmpty` is ok and will be productive, while `concatS after3Empty` will hang up?

I do.

> Using concatS, one can do more general things like asynchronously merging/zipping to MSFs etc.
> Are you saying we should somehow document this difference?

Definitely it should be documented.

And possibly even more. There two ways to classify this function: as a stream related function (although I think it can be generalised to MSFs), and as an asynchronous MSF function.

I'm wondering if all async stuff should be in an Async module. That's where I'd put it and where I'll put my long-overdue-to-be-pushed changes that also did asynchronous stuff.

**Comment by turion** [comment]
> I'm wondering if all async stuff should be in an Async module. That's where I'd put it and where I'll put my long-overdue-to-be-pushed changes that also did asynchronous stuff.

Oh yes, very good. Pushed.

**Comment by turion** [comment]
>> Do we agree that `concatS everyOtherEmpty` is ok and will be productive, while `concatS after3Empty` will hang up?

>I do.

I just checked, GHC does as well. And now the documentation even claims it! It must be true!

**Pull request merged**
