### PR TITLE
Removed Yampa's affine space definitions; made Dunai's internal

### PR DESCRIPTION
**Pull request by Linearity**
These changes address issues #172 and #13, and they work for me. The "dunai" package no longer exposes `Data.VectorSpace`. Now my `import Data.VectorSpace` statements are no longer ambiguous between the "dunai" and "simple-affine-space" packages.

Even with this change, `FRP.BearRiver` still re-exports `Data.VectorSpace`. I assume this is just for convenience, but it forces anyone using another vector space class with the same method names to resolve name conflicts whenever she imports `FRP.BearRiver`. In particular, it's inconvenient to use the "linear" package, with its class `Additive` and methods like `(^+^)`, alongside with `FRP.BearRiver`. I'd prefer just to import `Data.VectorSpace` on my own.

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
@Linearity / Alex Thanks!

If I understand this change correctly, this would make it impossible to define your own instances of vector space to use with bearriver's integral, right?

This indeed hints to a bigger issue with vector spaces (see #13), and it would probably be best, just to move forward, to stick to simple-affine-space and add any `RModule` or more interesting type there, until we can switch to a different library. 

I'll write on top of your commit to eliminate the need for `RModule` and dunai's `Data.VectorSpace` module before I merge this into develop.

Also, there's some binary .swp file (vim?) that should have been ignored by git. Different issue, though.

**Comment by ivanperez-keera** [comment]
@Linearity Does this work for you? https://github.com/ivanperez-keera/dunai/tree/Linearity-develop

**Comment by ivanperez-keera** [comment]
@turion If anyone is using dunai's `Data.VectorSpace`, it's you. Is this going to break all of your code?

**Comment by Linearity** [comment]
That branch does work for me. I don't understand those error messages from the continuous integration system. But the only checks I did were `stack build` and `stack build bearriver`, though, so maybe there's something else to check.

In my Yampa application I defined an orphan instance of `VectorSpace`, as defined in "simple-affine-space," for the "linear" package's `V2 Double` type that I'm using a lot. It allows me to run `integral` on signals of type `V2 Double`. The "Yampa" package does not provide the module `Data.VectorSpace`, so "dunai" not providing it either is OK. True, it does require me to use "simple-affine-space" knowing _a priori_ that Yampa uses the same package.

The `FRP.Yampa` module does re-export `Data.VectorSpace`, just as `FRP.BearRiver` does, but I removed that in my local version for the same reason I advocated removing it from `FRP.BearRiver` above.

**Comment by Linearity** [comment]
> Also, there's some binary .swp file (vim?) that should have been ignored by git. Different issue, though.
Yeah, sorry. I've been using darcs so much lately that I forgot that `git add` is the same as both `darcs add` and `darcs record`. Thanks for fixing it.

**Comment by ivanperez-keera** [comment]
So, this commit has been merged, but I put something on top and rebased. I'll close this, but you are still credited for your commit :) Thanks!

**Comment by turion** [comment]
>  If anyone is using dunai's `Data.VectorSpace` it's you. Is this going to break all of your code?

Yes, but this refactoring is worth it :)

**Pull request closed without merging**
